name: stress_management_app
description: bebe.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1 
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.0.0
  provider: ^6.0.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/leaf_top.png
    - assets/images/leaf_bottom.png