version: "3.9"

services:
  backend:
    build: 
      context: ./backend
    container_name: stress-backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: stress-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stress_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
