name: Frontend

on:
  push:
    branches: [main-*]
  pull_request:
    paths:
      - 'frontend**'
      - '.github/workflows/deploy.yml'

permissions:
  pull-requests: write
  contents: write

jobs:
  test:
    name: Run Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'

      - name: Install Flutter dependencies
        run: |
          cd frontend
          flutter pub get
          
      - name: Install dev dependencies
        run: flutter pub add mockito --dev

      - name: Run Flutter tests
        id: flutter-tests
        run: |
          cd frontend
          // First test
          echo "auth_passed=false" >> $GITHUB_OUTPUT
          
          
          if flutter test test/screens/add_session_screen_test.dart; then
            echo "session_passed=true" >> $GITHUB_OUTPUT
          fi
          
          
          

      - name: Calculate score
        id: score
        run: |
          TOTAL=0
          if [[ "${{ steps.flutter-tests.outputs.auth_passed }}" == "true" ]]; then TOTAL=$((TOTAL + 1)); fi
          echo "total=$TOTAL" >> $GITHUB_OUTPUT

      - name: Comment PR with score
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const score = ${{ steps.score.outputs.total }};
            const maxScore = 1;
            const percentage = (score / maxScore) * 100;
            
            const results = {
              'Flutter Tasks': {
                'Authentification': ${{ steps.flutter-tests.outputs.auth_passed }}
              }
            };
            
            for (const [category, tasks] of Object.entries(results)) {
              comment += `#### ${category}\n`;
              for (const [task, passed] of Object.entries(tasks)) {
                const status = passed ? '✅' : '❌';
                comment += `- ${status} ${task}\n`;
              }
              comment += '\n';
            }
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Create commit comment with score
        if: github.event_name == 'push'
        uses: actions/github-script@v7
        with:
          script: |
            const score = ${{ steps.score.outputs.total }};
            const maxScore = 1;
            const percentage = (score / maxScore) * 100;
            
            const results = {
              'Flutter Tasks': {
                'Authentification': ${{ steps.flutter-tests.outputs.auth_passed }}
              }
            };
            
            
            for (const [category, tasks] of Object.entries(results)) {
              comment += `#### ${category}\n`;
              for (const [task, passed] of Object.entries(tasks)) {
                const status = passed ? '✅' : '❌';
                comment += `- ${status} ${task}\n`;
              }
              comment += '\n';
            }
            
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: comment
            });
