name: Frontend CI

on:
  push:
    branches: [main-*]
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy.yml'

permissions:
  pull-requests: write
  contents: write

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'
          channel: 'stable'

      - name: Install dependencies
        run: |
          cd frontend
          flutter pub get

      - name: Run Flutter tests
        id: flutter-tests
        run: |
          cd frontend
          echo "add_session_passed=false" >> $GITHUB_OUTPUT
          
          # Run tests and capture exit code
          if flutter test test/add_session_screen_test.dart; then
            echo "add_session_passed=true" >> $GITHUB_OUTPUT
          fi

      - name: Calculate score
        id: score
        run: |
          TOTAL=0
          if [[ "${{ steps.flutter-tests.outputs.add_session_passed }}" == "true" ]]; then 
            TOTAL=$((TOTAL + 1))
          fi
          echo "total=$TOTAL" >> $GITHUB_OUTPUT
          echo "max_score=1" >> $GITHUB_OUTPUT

      - name: Comment PR with test results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const score = ${{ steps.score.outputs.total }};
            const maxScore = ${{ steps.score.outputs.max_score }};
            const percentage = Math.round((score / maxScore) * 100);
            
            let comment = `### 🧪 Frontend Test Results: ${score}/${maxScore} (${percentage}%)\n\n`;
            comment += `#### Flutter Tests\n`;
            
            const addSessionPassed = "${{ steps.flutter-tests.outputs.add_session_passed }}" === "true";
            comment += `- ${addSessionPassed ? '✅ PASSED' : '❌ FAILED'} Add Session Screen\n`;
            
            comment += `\n_Generated by GitHub Actions_`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Create commit comment
        if: github.event_name == 'push'
        uses: actions/github-script@v7
        with:
          script: |
            const score = ${{ steps.score.outputs.total }};
            const maxScore = ${{ steps.score.outputs.max_score }};
            const percentage = Math.round((score / maxScore) * 100);
            
            let comment = `### 🧪 Frontend Test Results: ${score}/${maxScore} (${percentage}%)\n\n`;
            comment += `#### Flutter Tests\n`;
            
            const addSessionPassed = "${{ steps.flutter-tests.outputs.add_session_passed }}" === "true";
            comment += `- ${addSessionPassed ? '✅ PASSED' : '❌ FAILED'} Add Session Screen\n`;
            
            comment += `\n_Generated by GitHub Actions_`;
            
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: comment
            });
